audio:
  input_device: null         # ALSA-enhetsindex eller null för standard
  sample_rate: 16000         # 16 kHz (Porcupine/Whisper/VAD)
  vad_aggressiveness: 2      # 0-3 (högre = klipper snabbare tystnad)
  max_utterance_sec: 12      # hård gräns på inspelningslängd
  silence_end_ms: 800        # avsluta efter så här mycket tystnad

wakeword:
  access_key_env: "PORCUPINE_ACCESS_KEY"
  keyword_path: "resources/porcupine/wakeword.ppn"
  model_path:   "resources/porcupine/porcupine_params_sv.pv"  # VALFRITT: svensk språkmodell (.pv). Om filen saknas används inbyggd standardmodell.
  sensitivity: 0.55          # 0.0 - 1.0

stt:
  model_dir: "resources/whisper/whisper-small-ct2"  # CT2-modellens katalog
  compute_type: "int8"       # int8, int8_float16, float16, float32
  language: "sv"
  beam_size: 5

tts:
  piper_bin: "/usr/local/bin/piper"
  model_path: "resources/piper/sv_SE-lisa-medium.onnx"
  keep_wav: false

mqtt:
  host: "7dab69000883410aba47967fb078d6d9.s1.eu.hivemq.cloud"
  port: 8883
  username_env: "MQTT_USERNAME"
  password_env: "MQTT_PASSWORD"
  client_id: "genio-ai-rpi5"
  ca_certs: null             # null = systemets CA (rekommenderas)
  tls_insecure: false
  qos: 1
  request_topic: "genioai/request"
  base_response_topic: "genioai/response"
  timeout_sec: 15
  keepalive: 60
  clean_session: true
