audio:
  input_device: null
  sample_rate: 16000
  vad_aggressiveness: 2
  max_utterance_sec: 12
  silence_end_ms: 800

wakeword:
  access_key_env: "PORCUPINE_ACCESS_KEY"
  keyword_path: "resources/porcupine/wakeword.ppn"
  sensitivity: 0.55

stt:
  model_dir: "resources/whisper/whisper-small-ct2"
  compute_type: "int8"
  language: "sv"
  beam_size: 5

tts:
  piper_bin: "/usr/local/bin/piper"
  model_path: "resources/piper/sv-voice.onnx"
  keep_wav: false

mqtt:
  host: "7dab69000883410aba47967fb078d6d9.s1.eu.hivemq.cloud"
  port: 8883
  username_env: "MQTT_USERNAME"
  password_env: "MQTT_PASSWORD"
  client_id: "genio-ai-rpi5"
  ca_certs: null
  tls_insecure: false
  qos: 1
  request_topic: "genioai/request"
  base_response_topic: "genioai/response"
  timeout_sec: 15
  keepalive: 60
  clean_session: true
